Ebony0wl/pikaboo

- README.md
> Hi, making changes.

- controllers/pokemons.js
- package-lock.json
- package.json
- routes/pokemon.js
- server.js
I set up the ground work for the first pokemonsController. Until views are properly created, they are only sending JavaScript Object Notation as a response back to the Client.
> Setup server.js and pokemonsController boilerplate

- controllers/evolutions.js
- controllers/generations.js
- controllers/locations.js
- controllers/maps.js
- controllers/types.js
- routes/evolutions.js
- routes/generations.js
- routes/location.js
- routes/maps.js
- routes/types.js
- server.js
For now, each controller only sends dummy text. Each is connected by index and show, which are crucial to be working first on both API and User Interface Implementation. Once those are complete for rendering, we can slowly work through POST routes one at a time.
> Create boilerplate routes and controllers

- controllers/pokemons.js
- package-lock.json
- package.json
Test promises to get api. After grabbing the response.data, the results array has elements that are pokemon objects. In ejs. we would access 'pokemon' like an array.
> Test pokemonsController#index with api

- controllers/pokemons.js
- package-lock.json
The Index was using promises (declarative syntax), while the show page is using async/await. The async await allowed me to assign a "foundPokemon" variable the axios.get values to better show anyone reading the code what is going on.
> Create pokemonsController#show response

- controllers/locations.js
- controllers/maps.js
- controllers/pokemons.js
- controllers/types.js
mapsController#index is in promises (declarative syntax)
We will have to render in maps/index.ejs
mapsController#show is written in async, await. The foundMap is retrieved from api via req.params.id
We will render in maps/show.ejs
Variables in maps/show.ejs
--------------
type: foundMap.data,
name: foundMap.data.names[5].name,
locations: foundMap.data.locations
> Define mapsControllers#index, #show, locationsController#index, #show

- controllers/evolutions.js
- controllers/generations.js
generationsController#index is in Promises (Declarative Syntax)
generationsController#show is an Async/Await Function.
Variables for generations/show.ejs
------
type: foundGeneration.data,
name: foundGeneration.data.main_region.name,
url: foundGeneration.data.main_region.url
> Create generationsController#index, generationsController#show, evolutionsController#index, evolutionsController#show

- controllers/items.js
- routes/items.js
- server.js
itemsController#index is in promises (declarative syntax)
itemsController#show is in async/await.
Variables in views/items/show.ejs
-----
```
type: foundItem.data,
name: foundItem.data.name,
category_name: foundItem.data.category.name,
sprites: foundItem.data.sprites
```
> Connect itemsRoutes; Create itemsController#index, itemsController#show

- controllers/moves.js
- routes/moves.js
- server.js
movesController#index is written in promises (declarative syntax).
movesController#show is written in async/await.
Variables in views/moves/show.ejs
----
```
move: foundMove.data,
name: foundMove.data.name,
type: foundMove.data.type,
accuracy: foundMove.accuracy
```
> Create movesController#index, #show

- controllers/pokemons.js
- package-lock.json
- package.json
- views/index.ejs
- views/partials/footer.ejs
- views/partials/header.ejs
- views/pokemons/pokemon_index.ejs
add pokemon_index.ejs file; edit css style link
> add pokemon_index.ejs

- controllers/pokemons.js
- public/style/style.css
- views/pokemons/pokemon_index.ejs
update controller & pokemon_index; fixed header:hover issue
> Update controller & pokemon_index

- public/style/style.css
- views/pokemons/pokemon_index.ejs
styling and position of elements; add card for pokemon info display
> fix positioning of elements

- config/firebase.js
- controllers/users.js
- package-lock.json
- package.json
- routes/users.js
- server.js
- views/signup/index.ejs
usersController actions are created and config/firebase.js is created. Awaiting instructions for proper firebase login.
> Create config/firebase and dummy signup (not linked to server.js yet)

- config/firebase.js
- controllers/auth.js
- controllers/users.js
- routes/auth.js
- routes/users.js
- server.js
- views/signin/index.ejs
- views/signup/index.ejs
- views/users/show.ejs
Firebase registration POST route not sending users properly to Firestore. Will be looking into this issue.
Login route works
> firebase sign-in works, firebase registration unreliable

- views/partials/header.ejs
- views/signup/index.ejs
added links; added required property to forms
> Updated Nav 

- config/firebase.js
- controllers/auth.js
- controllers/users.js
- package-lock.json
- package.json
- public/script/pokegotchi.js
- server.js
Tested a lot of random stuff here.
The doGetPokemon() is currently incomplete.
A pokegotchi.js was added as a static file.
> Firebase configs and Pokegotchi boilerplate

- controllers/pokemons.js
firebase#doGetPokemon should be complete
```
const userPokemon = await firebase.doGetPokemon(id);
//
//
//
//
//
//
res.render('pokemons/pokemon_index.ejs', {
name,
type,
generationName,
region,
chain,
pokemonPic,
userPokemon: userPokemon.data() || []
});
```
> Modify pokemonsController#show to get userPokemon from firestore

- controllers/pokemons.js
- routes/pokemon.js
```
router.get('/pokemon', pokemonsController.index);
router.post('/pokemon', pokemonsController.post);
router.get('/pokemon/:id', pokemonsController.show);
router.post('/pokemon/:id', pokemonsController.likePokemon);
router.delete('/pokemon/:id', pokemonsController.unlikePokemon);
```
```pokemonsController#likePokemon``` is a POST route
```pokemonsController#unlikePokemon``` is a DELETE route
> pokemonsController#likePokemon, #unlikePokemon

- public/script/allPokemon.js
public/script/allPokemon.js is an exported module that contains an array of Pokemon objects.
> Import script containing allPokemon

- public/style/style.css
- views/items/index.ejs
updated styling and progress on mobile responsiveness
> updated styling

- server.js
- views/signup/index.ejs
For form action - hit the correct routes/controller endpoint.
```/auth/signup```
```/auth/signin```
> Fix pathing/action errors in signup, signin views

- Procfile
- package.json
```npm run start``` "node server.js"
We have a ```Procfile``` that switches Heroku from Ruby to Node.js
> Create Procfile and add npm run start script for node server.js

- controllers/auth.js
- controllers/users.js
- server.js
Persistent session upon user login. If logged in, the user will be redirected to the User Show Page!
> req.session.user implementation

- public/style/style.css
- views/generations/generation.ejs
- views/signin/index.ejs
> style sheet update & sign in

- config/firebase.js
- controllers/auth.js
- views/signup/index.ejs
// ** User API **
```
doCreateUser = (id, user) => {
return this.db.collection('users').doc(id).set(user);
}
```
> Debug firebase config doCreateUser for (id, user)

- public/style/style.css
- views/items/show.ejs
- views/signup/index.ejs
- views/users/show.ejs
> mobile mini app implementation

- controllers/auth.js
- views/signup/index.ejs
Please ensure form action='/auth/signup' for signup/index.ejs
Please ensure form action='/auth/signin' for signin/index.ejs
```
// const heldPokemonData = axios.get(heldPokemonApi)
//                         .then((response) => {
//                         return response.data.results;
//                         })
//                         .catch( (err) => {
//                             console.log(err, <--- ' heldPokemonData error')
//                         })
// console.log(heldPokemonData);
// const heldPokemonObject = {
//     species: heldPokemonData.name,
//     timesFed: 0,
//     evolutionLevel: 0,
//     sprite: heldPokemonData.sprites,
// }
```
> Fix form actions for signup and signin, heldPokemon stuff in authController

- controllers/auth.js
```
const signIn = (req, res) => {
req.app.locals.err = '';
firebase.doSignInWithEmailAndPassword(req.body.email, req.body.password)
.then(authUser => {
console.log(authUser);
req.session.user = {
email: req.body.email,
id: authUser.user.uid,
heldPokemon: authUser.user.heldPokemon,
// heldPokemonData: authUser.user.heldPokemonData,
// heldPokemonName: authUser.user.heldPokemonName,
// heldPokemonSprite: authUser.user.heldPokemonSprite,
// heldPokemonObject: authUser.user.heldPokemonObject
}
res.redirect(`/users/${authUser.user.uid}`);
})
.catch(err => {
console.log(err);
res.app.locals.err = err.message;
res.redirect('/signin');
});
}
```
> Comment out dsabled properties on authController#signIn

- controllers/users.js
- public/script/script.js
- public/style/style.css
- routes/users.js
- views/items/index.ejs
- views/partials/header.ejs
- views/users/show.ejs
adding feeding button even and feeding function trigger
> adding feeding function

- views/users/show.ejs
> last minute fix

- public/style/style.css
- views/users/show.ejs
added text for nav bar
quick fix
> updated links
